export const randomUUID = () => crypto.randomUUID();
export const nativeApplicationVersion = '2.0.0-preview';
export const nativeBuildVersion = 'local';
export const setStringAsync = async (text) => navigator.clipboard.writeText(text);
export const fetchChatModels = async () => ['claude-sonnet-4', 'gpt-4.1', 'gemini-2.5-pro', 'gpt-image-2', 'gpt-image-2.5', 'gpt-image-2.5-flare', 'gpt-image-2.5-sunburst'];
export const getProviderKey = async () => 'preview-only';
export const saveProviderKey = async () => {};
export const upsertProvider = async () => {};
export const deleteLocalFile = async () => {};
export const saveToGallery = async () => {};
export const shareImage = async () => {};
export const validateAttachments = () => {};
export const networkFailureMessage = () => '本地预览不请求网络';
export const networkHost = (url) => new URL(url).hostname;
export const fetch = async () => ({ ok: true, status: 200 });
export const attachmentKind = (name) => /\.pdf$/i.test(name) ? 'pdf' : /\.(png|jpg)$/i.test(name) ? 'image' : /\.(docx|xlsx)$/i.test(name) ? 'office' : 'text';
export const isImageAttachment = (file) => file.mimeType.startsWith('image/');
const scene = '<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="800"><rect width="1200" height="800" fill="#e4eef6"/><circle cx="910" cy="180" r="83" fill="#faf6e9"/><path d="M0 630 360 200 720 680Z" fill="#aec4c5"/><path d="M250 700 740 290 1200 730Z" fill="#698d99"/><path d="M0 660 Q450 540 1200 700 V800H0Z" fill="#356171"/></svg>';
export const sampleImage = 'data:image/svg+xml;charset=utf-8,' + encodeURIComponent(scene);
export const pickFromGallery = async () => [{ id: randomUUID(), uri: sampleImage, name: '参考图片.png', mimeType: 'image/png', width: 1200, height: 800, size: 1024 }];
export const takePhoto = pickFromGallery;
export const pickFromFiles = pickFromGallery;
export const pickAnyFiles = async () => [{ id: randomUUID(), uri: 'preview:document', name: '品牌视觉设计方案.pdf', mimeType: 'application/pdf', size: 1240000 }];
export const createReferenceFromGenerated = async (uri) => ({ id: randomUUID(), uri, name: '参考图片.png', mimeType: 'image/png', width: 1200, height: 800, size: 1024 });
export const prepareReferenceForMask = async (image) => image;
export const prepareReferenceFromAttachment = async (image) => image;
