import { StyleSheet } from 'react-native';

import { themed } from '../theme';
import { mono } from './parts';

/** Styles shared by ThreadView and thread-rows, in the desktop look; follow light / dark. */
export const useThreadStyles = themed((c, d) => StyleSheet.create({
  apiLink: { fontSize: 12.5, fontWeight: '600', color: d.accentText }, parentLink: { paddingHorizontal: 10, paddingVertical: 4 },
  thumbs: { gap: 8, paddingBottom: 8 },
  thumb: { width: 56, height: 56, borderRadius: 12, overflow: 'hidden', backgroundColor: d.surface2 },
  thumbImage: { width: '100%', height: '100%' },
  thumbRemove: { position: 'absolute', top: 4, right: 4, width: 18, height: 18, borderRadius: 9, backgroundColor: 'rgba(14,19,37,0.72)', alignItems: 'center', justifyContent: 'center' },
  userImages: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'flex-end', gap: 6, marginBottom: 6, maxWidth: '86%' },
  userImage: { width: 96, height: 96, borderRadius: 14, backgroundColor: d.surface2 },
  modelChip: { flexDirection: 'row', alignItems: 'center', gap: 5, height: 28, paddingHorizontal: 9, borderRadius: 14, backgroundColor: d.surface3, maxWidth: 170 },
  plan: { borderRadius: 16, borderWidth: 1, borderColor: d.line, backgroundColor: d.surface2, paddingHorizontal: 14, paddingVertical: 12, gap: 8 },
  planHead: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  planTitle: { color: d.text, fontSize: 14, fontWeight: '700', flex: 1 },
  planCount: { color: d.muted, fontSize: 12.5, fontWeight: '600' },
  planRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 10 },
  planDot: { width: 16, height: 16, borderRadius: 8, borderWidth: 1.5, borderColor: d.faint, marginTop: 2, alignItems: 'center', justifyContent: 'center' },
  planDotDone: { backgroundColor: d.accent, borderColor: d.accent },
  planDotActive: { borderColor: d.accent, borderWidth: 4 },
  planText: { flex: 1, color: d.text2, fontSize: 14, lineHeight: 20 },
  planTextDone: { color: d.muted, textDecorationLine: 'line-through' },
  planTextActive: { color: d.text, fontWeight: '600' },
  list: { paddingHorizontal: 18, paddingTop: 12, paddingBottom: 20, gap: 14 },
  loading: { alignItems: 'center', gap: 10, paddingVertical: 64 },
  loadingText: { color: d.muted, fontSize: 13.5 },
  thinking: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingVertical: 4 },
  thinkingText: { color: d.muted, fontSize: 13.5 },
  userRow: { alignItems: 'flex-end' },
  userBubble: { maxWidth: '86%', backgroundColor: d.userBubble, borderRadius: 20, paddingHorizontal: 15, paddingVertical: 10 },
  userText: { color: d.text, fontSize: 15.5, lineHeight: 23 },
  assistant: { paddingRight: 2 },
  work: { gap: 6 },
  subagent: { gap: 6, paddingVertical: 6 }, subagentTitle: { flex: 1, color: d.muted, fontSize: 13.5, fontWeight: '500' },
  workHead: { flexDirection: 'row', alignItems: 'center', gap: 8, minHeight: 28 },
  workTitle: { flexShrink: 1, color: d.muted, fontSize: 13.5, fontWeight: '500' },
  workBody: { borderLeftWidth: 2, borderColor: d.line, marginLeft: 6, paddingLeft: 12, gap: 2 },
  step: { flexDirection: 'row', alignItems: 'center', gap: 8, minHeight: 30 },
  stepText: { flex: 1, color: d.muted, fontSize: 13, fontFamily: undefined },
  reasoning: { flex: 1, color: d.muted, fontSize: 13, lineHeight: 19, fontStyle: 'italic', paddingVertical: 4 },
  output: { marginLeft: 22, marginBottom: 6, borderRadius: 12, backgroundColor: d.code, padding: 11, gap: 6 },
  outputCmd: { fontFamily: mono, fontSize: 12, lineHeight: 18, color: '#9FE7C4' },
  outputText: { fontFamily: mono, fontSize: 11.5, lineHeight: 17, color: d.codeText },
  exit: { fontFamily: mono, fontSize: 11, color: '#FF8A8A' },
  files: { borderRadius: 14, borderWidth: StyleSheet.hairlineWidth, borderColor: d.line, backgroundColor: d.surface2, paddingHorizontal: 12, paddingVertical: 4 },
  file: { flexDirection: 'row', alignItems: 'center', gap: 8, minHeight: 36 },
  fileName: { flex: 1, color: d.text, fontSize: 13.5, fontFamily: mono },
  stat: { fontFamily: mono, fontSize: 12, fontWeight: '600' },
  notice: { flexDirection: 'row', alignItems: 'center', gap: 8, borderRadius: 12, paddingHorizontal: 12, paddingVertical: 9, backgroundColor: d.surface2 },
  noticeError: { backgroundColor: d.badSoft },
  noticeText: { flex: 1, color: d.muted, fontSize: 13, lineHeight: 19 },
  intro: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 28, gap: 8 },
  introIcon: { width: 48, height: 48, borderRadius: 16, alignItems: 'center', justifyContent: 'center', backgroundColor: d.surface3, marginBottom: 4 },
  introTitle: { color: d.text, fontSize: 20, fontWeight: '700', letterSpacing: -0.4 },
  introDetail: { color: d.muted, fontSize: 13, lineHeight: 19, textAlign: 'center' },
  introProject: { flexDirection: 'row', alignItems: 'center', gap: 7, marginTop: 12, height: 36, paddingHorizontal: 14, borderRadius: 18, backgroundColor: d.surface2, borderWidth: StyleSheet.hairlineWidth, borderColor: d.line, maxWidth: '90%' },
  introProjectText: { color: d.text, fontSize: 13.5, fontWeight: '600', flexShrink: 1 },
  introPath: { color: d.faint, fontSize: 12, maxWidth: '90%' },
  composerWrap: { paddingHorizontal: 10, paddingTop: 4, paddingBottom: 8, gap: 6 },
  banner: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 12, paddingVertical: 8, borderRadius: 14, backgroundColor: d.surface2, borderWidth: StyleSheet.hairlineWidth, borderColor: d.line },
  bannerText: { flex: 1, color: d.text2, fontSize: 12, lineHeight: 17 },
  composer: { backgroundColor: d.surface, borderRadius: 22, borderWidth: StyleSheet.hairlineWidth, borderColor: d.lineStrong, paddingTop: 4, shadowColor: d.shadow, shadowOpacity: 0.05, shadowRadius: 12, shadowOffset: { width: 0, height: 2 }, elevation: 1 },
  chipRow: { flexDirection: 'row', gap: 6, paddingHorizontal: 10, paddingTop: 4, flexWrap: 'wrap' },
  input: { minHeight: 40, maxHeight: 150, color: d.text, paddingHorizontal: 14, paddingTop: 8, paddingBottom: 4, fontSize: 15, lineHeight: 21 },
  readOnlyBar: { flexDirection: 'row', alignItems: 'center', gap: 10, marginHorizontal: 12, marginBottom: 8, paddingVertical: 10, paddingLeft: 14, paddingRight: 8, borderRadius: 16, backgroundColor: d.surface2 },
  readOnlyTitle: { fontSize: 12, fontWeight: '600', color: d.text2 }, readOnlyText: { fontSize: 11.5, color: d.muted, marginTop: 1 },
  continueButton: { flexDirection: 'row', alignItems: 'center', gap: 5, height: 32, paddingHorizontal: 12, borderRadius: 16, backgroundColor: d.surface, borderWidth: StyleSheet.hairlineWidth, borderColor: d.lineStrong },
  continueText: { fontSize: 12.5, fontWeight: '600', color: d.text },
  seedRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginHorizontal: 12, marginTop: 6, paddingHorizontal: 10, height: 26, borderRadius: 13, backgroundColor: d.accentSoft, alignSelf: 'flex-start', maxWidth: '92%' },
  seedText: { fontSize: 11.5, color: d.accentText, flexShrink: 1 },
  composerBar: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 7, paddingBottom: 7 },
  chip: { flexDirection: 'row', alignItems: 'center', gap: 5, height: 28, paddingHorizontal: 9, borderRadius: 14, backgroundColor: d.surface3, maxWidth: 170 },
  chipText: { color: d.text2, fontSize: 12, fontWeight: '500', flexShrink: 1 },
  send: { width: 34, height: 34, borderRadius: 17, alignItems: 'center', justifyContent: 'center' },
  stop: { backgroundColor: d.ink },
  approvalWrap: { paddingHorizontal: 12, paddingBottom: 4 },
  approval: { borderRadius: 22, backgroundColor: d.surface, paddingHorizontal: 14, paddingTop: 12, paddingBottom: 12, gap: 10, borderWidth: StyleSheet.hairlineWidth, borderColor: d.lineStrong, shadowColor: d.shadow, shadowOpacity: 0.1, shadowRadius: 22, shadowOffset: { width: 0, height: 8 }, elevation: 6 },
  approvalHead: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  approvalBadge: { flexDirection: 'row', alignItems: 'center', gap: 5, height: 24, paddingHorizontal: 9, borderRadius: 12, backgroundColor: d.warnSoft, maxWidth: '72%' },
  approvalKicker: { color: d.warn, fontSize: 11.5, fontWeight: '600', flexShrink: 1 },
  approvalTitle: { color: d.text, fontSize: 15.5, lineHeight: 22, fontWeight: '600' },
  moreBadge: { paddingHorizontal: 8, height: 22, borderRadius: 11, justifyContent: 'center', backgroundColor: d.surface3 },
  moreText: { color: d.muted, fontSize: 11.5, fontWeight: '600' },
  approvalDetail: { fontFamily: mono, fontSize: 12, lineHeight: 18, color: d.text2, backgroundColor: d.surface2, borderRadius: 12, paddingHorizontal: 12, paddingVertical: 10 },
  approvalActions: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingTop: 2 },
  decision: { height: 38, borderRadius: 19, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 16 },
  decisionDeny: { backgroundColor: 'transparent', paddingHorizontal: 8 },
  decisionSoft: { backgroundColor: d.surface3 },
  decisionAllow: { backgroundColor: d.ink, minWidth: 76 },
  decisionText: { color: d.text, fontSize: 14, fontWeight: '600' },
  highlight: { marginHorizontal: -8, paddingHorizontal: 8, paddingVertical: 4, borderRadius: 14, backgroundColor: d.warnSoft },
  retry: { flexDirection: 'row', alignItems: 'center', gap: 4, height: 28, paddingHorizontal: 10, borderRadius: 14, backgroundColor: d.surface },
  retryText: { color: d.accentText, fontSize: 12.5, fontWeight: '600' },
  fullDiff: { flexDirection: 'row', alignItems: 'center', gap: 5, alignSelf: 'flex-start', paddingVertical: 2 },
  workClock: { color: d.faint, fontSize: 12, fontVariant: ['tabular-nums'] },
  queued: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingLeft: 12, paddingRight: 6, paddingVertical: 7, borderRadius: 14, backgroundColor: d.accentSoft },
  queuedText: { color: d.text, fontSize: 13, fontWeight: '500' },
  queuedHint: { color: d.accentText, fontSize: 11.5, marginTop: 1 },
  queuedClose: { width: 28, height: 28, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  renameInput: { height: 44, borderRadius: 14, backgroundColor: d.surface3, paddingHorizontal: 14, color: d.text, fontSize: 15, marginTop: 8 },
  reason: { minHeight: 72, borderRadius: 14, backgroundColor: d.surface3, paddingHorizontal: 14, paddingVertical: 10, color: d.text, fontSize: 15, marginTop: 8, textAlignVertical: 'top' },
}));
